
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 16 22:09:55 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 37;
  public static final int LTE = 44;
  public static final int LBRACKET = 12;
  public static final int CONST = 7;
  public static final int NUMCONST = 11;
  public static final int LPAREN = 3;
  public static final int SEMI = 18;
  public static final int CONTINUE = 25;
  public static final int MINUS = 34;
  public static final int RPAREN = 4;
  public static final int AND = 33;
  public static final int LT = 43;
  public static final int VALASS = 10;
  public static final int RECORD = 19;
  public static final int OR = 32;
  public static final int COMMA = 8;
  public static final int CLASS = 14;
  public static final int INC = 30;
  public static final int PLUS = 35;
  public static final int IF = 47;
  public static final int THIS = 51;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int EQUAL = 45;
  public static final int RBRACKET = 13;
  public static final int SUPER = 49;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int BREAK = 24;
  public static final int IDENT = 5;
  public static final int VOID = 20;
  public static final int GTE = 42;
  public static final int MULTIPLE = 36;
  public static final int COLON = 21;
  public static final int ELSE = 48;
  public static final int LBRACE = 16;
  public static final int ENUM = 50;
  public static final int READ = 27;
  public static final int GOTO = 29;
  public static final int CHARCONST = 6;
  public static final int WHILE = 23;
  public static final int RBRACE = 17;
  public static final int BOOLCONST = 9;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int DIFF = 46;
  public static final int DEC = 31;
  public static final int GT = 41;
  public static final int MODUL = 38;
  public static final int PRINT = 28;
  public static final int DO = 22;
}

